modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="create_rocketry"
version="${mod_version}"
displayName="${mod_name}"
authors="Soylebres & Meepy"


description='''funni goofy create space mod'''

[[dependencies.create_rocketry]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.create_rocketry]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.create_rocketry]]
modId="create"
mandatory=true
versionRange="[0.5.1.f,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_rocketry]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"

modLoader="kotlinforforge"
loaderVersion="[4.10,)"